"""add uninfo tables

迁移 ID: 0d35f4a55507
父迁移: 
创建时间: 2025-09-17 11:45:02.187770

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0d35f4a55507'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_uninfo_botmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('self_id', sa.String(length=64), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_uninfo_botmodel')),
    sa.UniqueConstraint('self_id', 'adapter', name='nonebot_plugin_uninfo_unique_bot'),
    info={'bind_key': ''}
    )
    op.create_table('nonebot_plugin_uninfo_scenemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_persist_id', sa.Integer(), nullable=False),
    sa.Column('parent_scene_persist_id', sa.Integer(), nullable=True),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('scene_type', sa.Integer(), nullable=False),
    sa.Column('scene_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_uninfo_scenemodel')),
    sa.UniqueConstraint('bot_persist_id', 'scene_id', 'scene_type', name='nonebot_plugin_uninfo_unique_scene'),
    info={'bind_key': ''}
    )
    op.create_table('nonebot_plugin_uninfo_sessionmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_persist_id', sa.Integer(), nullable=False),
    sa.Column('scene_persist_id', sa.Integer(), nullable=False),
    sa.Column('user_persist_id', sa.Integer(), nullable=False),
    sa.Column('member_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_uninfo_sessionmodel')),
    sa.UniqueConstraint('bot_persist_id', 'scene_persist_id', 'user_persist_id', name='nonebot_plugin_uninfo_unique_session'),
    info={'bind_key': ''}
    )
    op.create_table('nonebot_plugin_uninfo_usermodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_persist_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_uninfo_usermodel')),
    sa.UniqueConstraint('bot_persist_id', 'user_id', name='nonebot_plugin_uninfo_unique_user'),
    info={'bind_key': ''}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_uninfo_usermodel')
    op.drop_table('nonebot_plugin_uninfo_sessionmodel')
    op.drop_table('nonebot_plugin_uninfo_scenemodel')
    op.drop_table('nonebot_plugin_uninfo_botmodel')
    # ### end Alembic commands ###
